# Generated by Django 6.0.6 on 2026-06-11 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video_key', models.CharField(blank=True, max_length=500)),
                ('audio_key', models.CharField(blank=True, max_length=500)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ml', 'Malayalam'), ('mixed', 'Mixed')], default='en', max_length=10)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('TRANSCRIBED', 'Transcribed'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('english_transcript', models.TextField(blank=True)),
                ('malayalam_transcript', models.TextField(blank=True)),
                ('detected_language', models.CharField(blank=True, max_length=10)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('text', models.TextField(blank=True)),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('is_processed', models.BooleanField(default=False)),
                ('embedding_id', models.CharField(blank=True, max_length=200)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='videos.video')),
            ],
            options={
                'ordering': ['chunk_index'],
                'unique_together': {('video', 'chunk_index')},
            },
        ),
    ]
