# Generated by Django 6.0.6 on 2026-06-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptchunk',
            name='topic_segment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='english_pdf_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='malayalam_pdf_key',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
